### ISSUE TITLE
Allow configuration of attributes in hclpspec

### ISSUE THREAD

**Issue by einsiedlerkrebs** [bsdpot/nomad-pot-driver#37]
With the current workflow a attribute of a pot is only set during the creation as an image. This works for single purpose images. 
Single purpose pots are bringing some overhead in storage and bandwidth use and therefore I ship pots which are representing a group of software, but only single ones are execute in the end. 
Since it is not possible, to set attributes in Nomads job configuration a attribute for one piece of software is used for each one which relies on this image. 

I would prefer that it would be possible, to have attributes configurable in a nomad job configuration as well, so that I don't need to define/build/ship/store an extra pot image in order to apply a certain attribute. 

as an example: 
I am having a group pot image `transport` which should be the template to execute OpenVPN and Nginx. Nginx does not need any special attributes but for OpenVPN I need a certain `defvs_ruleset`  ( bsdpot/pot#269 ) in order to have access to hosts `/dev/tun` interface. Since I am able to configure mounts, command and arguments in my opinion it would be consequent to have configurable attributes follow this path. 

Thanks for having a look and for this piece of software anyway!

**Comment by einsiedlerkrebs** [comment]
... been a while. 

and in your nomad job spec you address a pot with a specific attribute set lets say: MultiPurpose_with_devFS_rulset3 as a base image, from which the worker pot is cloned from?!

**Comment by grembo** [comment]
> ... been a while.
> 
> and in your nomad job spec you address a pot with a specific attribute set lets say: MultiPurpose_with_devFS_rulset3 as a base image, from which the worker nomad task runner pot is cloned from?!
> 
> My question is which/how many images you "ship" in the end. Either you prepare everything upstream and need to download everything for little purpose

What you would download is very small in this case (since it's layered), fully loaded (so misconfiguration wouldn't be a thing), and - ideally - tested. So you won't need necessarily to know that the devfs_ruleset should be exported, as the openvpn image should do that for you.

This doesn't mean I'm against such features, I just wanted to show how I would address the specific issue - for these kinds of features it would definitely also make sense to add plugin configuration on clients, so that they can be turned off for security reasons.
